### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by Motokoder** [dfinity/exchange-rate-canister#137]
Duplicate code:
```
let okx = Okx;
assert!(okx.supports_ipv6());
let okx = Okx;
assert!(okx.supports_ipv6());
```
https://github.com/dfinity/exchange-rate-canister/blob/6af2af5cccaefde0e0128ae1b3d0a90c95946868/src/xrc/src/exchanges.rs#L495

**Comment by THLO** [comment]
Good catch! It'll be fixed in an upcoming PR.

**Comment by THLO** [comment]
Fixed in [this PR](https://github.com/dfinity/exchange-rate-canister/pull/141).
